version: '3.8'

services:
  uniswap:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: uniswap
      POSTGRES_PASSWORD: uniswap
      POSTGRES_DB: uniswap
    ports:
      - "5432:5432"
