version: '3.8'

services:
  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_USER: uniswap
      POSTGRES_PASSWORD: uniswap
      POSTGRES_DB: uniswap
    ports:
      - "5432:5432"
      
  rabbitmq:
      image: rabbitmq:3.8
      ports:
        - "5672:5672"
        - "15672:15672"
